### ISSUE TITLE
Modifications not taking effect

### ISSUE THREAD

**Issue by sede-fa** [CATIA-Systems/Modelica-ExternalLibrary#10]
Problem: When trying to change the python function and method to test if any change to the module will be seen in modelica, I saw that there was now change.
For example, when changing the function which returned `tuple(v + k for v in u)` to `tuple(v + 2* k for v in u)` I was expecting `y[1]` to give 6, instead it remained as 3.
Also adding in another function to do this also did not work as it gave the error message "function name must be external_library_function" 

Installation procedure:
I am quite new to building Cpp projects so maybe I messed up along the way. but I did the process a little different than outlined on the readme as I can't install the cmake-gui. my steps were:
1. change the cmakeLists.txt to put Python and the path to my conda environment
2. open VS command prompt and `cd ./Modelica_ExternalLibrary/build`
3. `cmake ../` to configure and generate
4. `cmake --build .` to build and confirmed the .dll file was generated
5. I tried the ExternalLibrary_test.cpp but it kept failing because it could not first find the include files (I then used the absolute path to bypass this, and then it failed because I could not find variables such as PYTHON_HOME etc. that is passed into the function)

After Installation:
So then I moved straight to the modelica library and encountered the above issue.
I first ran the example models as they were and they both ran fine, suggesting that something is reading this data file (I also changed the value in the data file and this worked fine

Seeing as In the 4 years of this project existing, I have not seen another issue like this, its pretty clear I messed up somewhere. Is there a way I can fix this?

Further notes:
It seems that even if I don't set the PYTHONHOME variable, the model is still running. I would have expected a failure here. Also in the case where the python library is not installed in the conda-env.

**Comment by t-sommer** [comment]
Why can‘t you use the CMake GUI and follow the steps in the readme?

**Comment by sede-fa** [comment]
We have restrictions with what software we can install

**Comment by sede-fa** [comment]
I've managed to use the prebuilt version of the cmake-gui (the .zip files) and after following the instructions I can confirm that the modifications are working, even with importing external  packages such as numpy. 

Sorry for the inconvenience!
