### ISSUE TITLE
Simulation crashes during initialization

### ISSUE THREAD

**Issue by JandaO** [CATIA-Systems/Modelica-ExternalLibrary#2]
Hi!
I get the following problem when setting up the external library package:
First of all, I previously managed to get the package working on two other computers. On one of them, I compiled the dll files with CMake for Windows 64bit in the first place.
So, I copy the complete package folder structure from one of the computers where it is working to the new one, in order to save the hassle of compiling the dll files again. On the new computer, I have the following environment:
-  Windows 10 Enterprise Ver. 1809 64bit
- Dymola 2021 64bit
- Anaconda 3 containing Python 3.8.3 64bit
Whereas on the computer where I copied the files from I have
- Windows 10 Enterprise Ver. 1909 64bit
- Dymola 2020x 64bit
- Anaconda 3 containing Python 3.7.3 64bit

Then, I execute the following steps

1. Enter "pip install -e Python" in the root of the repository (I get a success message)
2. Open Dymola and set the working directory to the folder Modelica_ExternalLibrary-master
3. Load package.mo
4. Insert the following two commands in the Dymola command line:
   Advanced.CompileWith64=2
   Modelica.Utilities.System.setEnvironmentVariable("PYTHONHOME", "C:/Programs/Anaconda3") 
   (the path to the Anaconda installation is correct for my computer)
5. Open the model ExternalLibraryObjectExample
6. Start Simulation

What then happens is that after a successful compilation, the simulation crashes during initialization, i.e. I get the error message "Process Simulation: Initialization stopped without any error indication." 
(For some reason, I get an error message when I try to upload a screenshot of the situation, but I sent you the screenshot via Email before.) 

I uploaded the buildlog:
[buildlog.txt](https://github.com/CATIA-Systems/Modelica-ExternalLibrary/files/5671530/buildlog.txt)

What I also tested was creating an ExternalLibrary Object directly from the Python console and executing its evaluate function. This works fine.

Thanks for the support!

Oliver

**Comment by t-sommer** [comment]
Do you get an error message when you run the `dymosim.exe` on the command line?

**Comment by JandaO** [comment]
This is what I get when I execute dymosim.exe from the command line:

dymosim started
... "dsin.txt" loading (dymosim input file)

and then, a pop-up windows appears, telling me that dymosim crashed.

**Comment by t-sommer** [comment]
Does the Python version on the target machine match exactly the version the DLL was linked against?

**Comment by JandaO** [comment]
No, it didn't. We compiled for Python 3.7, whereas on the computer version 3.8 was installed. We re-compiled the dll files and it worked. 
Thank you so much!
