### ISSUE TITLE
Simulation crashes when external python function gets called multiple times and numpy is imported in pyhton module

### ISSUE THREAD

**Issue by claxerity** [CATIA-Systems/Modelica-ExternalLibrary#8]
The simulation crashes when an external python function gets called multiple times through externalLibraryFunction.mo and numpy gets imported in the corresponding python module. This problem can also be reproduced by a small change in the c-code unit test of the external function. So the problem should not be due to Modelica.

I created a minimal example based on the externalLibrary: https://github.com/claxerity/Modelica-ExternalLibrary/tree/bug/reproduce_numpy_error

The error message in Dymola is:

dymosim started
... "ExternalLibrary.ExternalLibraryFunctionExample_numpyIssue" simulating
... "dsin.txt" loading (dymosim input file)
Error: The following error was detected at time: 0
  \objects\structseq.c:401: bad argument to internal function
  Failed condition: Modelica.Utilities.Strings.isEmpty(errorMessage)
The stack of functions is:
ExternalLibrary.externalLibraryFunction
ExternalLibrary.externalLibraryFunction(Dymola_ResolveURI("modelica://ExternalLibrary/Resources/Data/data.txt"), "external_library", "external_library_function", ModelicaInternal_getenv("PYTHONHOME", false), {1, 3})

**Comment by t-sommer** [comment]
This seems to be related to https://stackoverflow.com/questions/63576669/python-c-api-error-restarting-interpreter.

You can use the `ExternalLibraryObject` to make multiple calls into Python.
